version: '3.3'
services:
  wallabag:
    image: wallabag/wallabag:latest
    container_name: wallabag
    restart: always
    networks:
      - homelab
    healthcheck:
      test: "curl --fail -I http://localhost/api/info.json || exit 1"
      interval: 15s
      timeout: 5s
    volumes:
      - wallabag-data:/var/www/wallabag/data
      - wallabag-images:/var/www/wallabag/web/assets/images
    environment:
      - "SYMFONY__ENV__DOMAIN_NAME=http://bookmarks.home.lan"
    dns:
      - 172.18.0.1
      - pihole

volumes:
  wallabag-data:
  wallabag-images:

networks:
  homelab:
    external: true
