version: '3.4'
services:
  netbox:
    container_name: netbox
    ports:
      - 8000:8080
    healthcheck:
      test: "curl --fail -I http://localhost:8080/api/status/ || exit 1"
      interval: 10s
      timeout: 3s
    dns:
      - 172.18.0.1
      - pihole
    networks:
      - homelab
  netbox-worker:
    container_name: netbox_worker
    healthcheck:
      test: ""
    networks:
      - homelab
  postgres:
    container_name: netbox_pg
    networks:
      - homelab
  redis:
    container_name: netbox_redis
    networks:
      - homelab
  redis-cache:
    container_name: netbox_redis-cache
    networks:
      - homelab
networks:
  homelab:
    external: true

volumes:
  netbox-media-files:
    external: true
  netbox-postgres-data:
    external: true
  netbox-redis-data:
    external: true
