version: '3.4'
services:
  netbox:
    container_name: netbox
    healthcheck:
      test: "curl --fail -I http://localhost:8080/api/status/ || exit 1"
      interval: 30s
      timeout: 3s
    restart: unless-stopped
    dns:
      - 10.10.1.162
    networks:
      - homelab
  netbox-worker:
    container_name: netbox_worker
    restart: unless-stopped
    healthcheck:
      test: ""
    networks:
      - homelab
  postgres:
    container_name: netbox_pg
    restart: unless-stopped
    networks:
      - homelab
  redis:
    container_name: netbox_redis
    restart: unless-stopped
    networks:
      - homelab
  redis-cache:
    container_name: netbox_redis-cache
    restart: unless-stopped
    networks:
      - homelab
networks:
  homelab:
    external: true

volumes:
  netbox-media-files:
    external: true
  netbox-postgres-data:
    external: true
  netbox-redis-data:
    external: true
