version: "2"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    domainname: pihole.docker
    restart: unless-stopped
    shm_size: '2gb'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9080:80/tcp"
    environment:
      - TZ='America/Chicago'
      - WEBPASSWORD="${WEBPASSWORD}"
      - VIRTUAL_HOST='dns.home.lan'
    networks:
      - homelab
    volumes:
      - pihole:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/

networks:
  homelab:
    external: true

volumes:
  pihole:
    external: true
  pihole_dnsmasq:
    external: true

