version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - '81:81'
      - '443:443'
    environment:
      - DISABLE_IPV6='true'
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    volumes:
      - nginxproxymanager_data:/data
      - nginxproxymanager_le:/etc/letsencrypt
    networks:
      - homelab
    restart: unless-stopped
    dns:
      - 172.18.0.1
      - pihole

volumes:
  nginxproxymanager_data:
    external: true
  nginxproxymanager_le:
    external: true
networks:
  homelab:
    external: true
